api:
  key: ${API_KEY}
  url: ${BASE_URL}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchangerates
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true